### ISSUE TITLE
Help:Problem with updating root policy 

### ISSUE THREAD

**Issue by vasmarg** [authzforce/server#13]
Hi,

When trying to update my root policy I get a message telling me that the content of the new policy is invalid. I figured out that the problem was in the Condition that I used ( commenting that would prevent the error). Any ideas on what could be a potential error.  

My Condition:
`           <ns4:Condition>
                <ns4:Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:and">
                    <ns4:Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:integer-greater-than-or-equal">                        
                        <ns4:AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:1.0:subject:age" Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject" DataType="http://www.w3.org/2001/XMLSchema#integer" MustBePresent="true"/>                    
                        <ns4:AttributeValue DataType="http://www.w3.org/2001/XMLSchema#integer">10</ns4:AttributeValue>
                    </ns4:Apply>
                    <ns4:Apply FunctionId="urn:oasis:names:tc:xacml:1.0:function:integer-less-than-or-equal">
                        <ns4:AttributeDesignator AttributeId="urn:oasis:names:tc:xacml:1.0:subject:age" Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject" DataType="http://www.w3.org/2001/XMLSchema#integer" MustBePresent="true"/>
                        <ns4:AttributeValue DataType="http://www.w3.org/2001/XMLSchema#integer">40</ns4:AttributeValue>
                    </ns4:Apply>
                </ns4:Apply>    
            </ns4:Condition> `

**Comment by cdanger** [comment]
Could you give me full error message?

**Comment by vasmarg** [comment]
Thx! Indeed that was the cause of error.

Here is the error that I got :

`< HTTP/1.1 100 Continue
< HTTP/1.1 400 Bad Request
* Server Apache-Coyote/1.1 is not blacklisted
< Server: Apache-Coyote/1.1
< Date: Thu, 19 Jan 2017 13:18:29 GMT
< Content-Type: application/xml;charset=UTF-8
< Content-Length: 504
< Connection: close
< 
* Closing connection 0
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><error xmlns="http://authzforce.github.io/rest-api-model/xmlns/authz/5" xmlns:ns2="http://www.w3.org/2005/Atom" xmlns:ns3="http://authzforce.github.io/core/xmlns/pdp/5.0" xmlns:ns4="http://authzforce.github.io/pap-dao-flat-file/xmlns/properties/3.6"><message>Failed to find a root PolicySet with id = xatt, Version=*,EarliestVersion=*,LatestVersion=*: Matched PolicySet 'xatt' (version 1.6) is invalid or its content is unavailable</message></error>`
