### ISSUE TITLE
Policy editor UI

### ISSUE THREAD

**Issue by amemon** [authzforce/server#17]
Hi,

is it possible to perform operations on policies (e.g. CRUD) and domains with some WebUI (apart from the REST interface)? in addition to that, can one (graphically) assign domains or policy sets to a particular set of users to manage their application related policies? Furthermore, do you plan to implement such UI?
 
Please also note that I have a separate user identity management server in place, which can act as a SAML IdP and/or OAuth2/OIDC authorization server. So, if there exists a authzforce UI that understands any of the given protocols, the integration of authzforce and the idm can be realised.

Thanks,
Shiraz

**Comment by cdanger** [comment]
AuthzForce itself does not provide any user interface and this is not on the roadmap for the moment. However, one of our partners provides an [identity & access management solution (KeyRock, aka FIWARE IdM)](http://fiware-idm.readthedocs.io/en/v5.4.0/introduction.html) with such a WebUI to manage a role-based policy per application in AuthzForce server backend.  Besides, AuthzForce Server's REST API supports JSON format that you can leverage to develop your own Javascript-based WebUI. This could be a better option if you want to integrate the UI with the identity and access management server you already have.

For assigning domains/policysets, you may use the user-role or user-group assignment feature of your identity manager (a good one has it usually). For example, you create and assign a role/group named _DomainAdmin.A0bdIbmGEeWhFwcKrC9gSQ_ to user _Bob_, to say Bob is administrator of AuthzForce domain _A0bdIbmGEeWhFwcKrC9gSQ_. 

You need an "administrative" policy that defines permissions for such roles, e.g. _users with role_ DomainAdmin.A0bdIbmGEeWhFwcKrC9gSQ _may do all actions on URL path starting with_ /authzforce-ce/domains/A0bdIbmGEeWhFwcKrC9gSQ . You can also do it in a more generic way with XACML variables (any role `DomainAdmin.${domainId}` can do anyting on path starting with `/authzforce-ce/domains/${domainId}`). See the sample [admin policy in the source](../blob/develop/webapp/src/test/resources/xacml.samples/admin/policy.xml) for example. This is advanced XACML so you may try to do it without variables, before you try this one if you are not quite familiar with XACML.

Then you need a PEP (e.g. reverse proxy) protecting AuthzForce Server's REST API, i.e. that is able to intercept REST API requests to the server, authenticate, and extract URL/path, method, header, etc. and user info from the authentication context, including the user roles/groups (that may be retrieved from your IdM using the user ID, or from the authentication token in the request, depending on the authentication method), then pass all this info in a XACML request to a special dedicated PDP. Let's call it the "administrative" PDP. For such PDP, you can also use AuthzForce of course (e.g. in a special "admin" domain on AuthzForce Server, or embedded in the PEP using AuthzForce Core's Java library if the PEP is Java-based).  Anyway, it must be configured to use the "administrative" policy mentioned earlier.
Again, one of our partners (the same one that provides the aforementioned KeyRock) provides such a PEP for REST APIs that already integrates with AuthzForce Server: [Wilma, aka FIWARE PEP Proxy](https://catalogue.fiware.org/enablers/pep-proxy-wilma).

**Comment by amemon** [comment]
Thank you very much for a very detailed response.
