### ISSUE TITLE
Bulk import XACML policies

### ISSUE THREAD

**Issue by amemon** [authzforce/server#18]
Hi,

Is it possible to bulk import xacml 3.0 policies into the server database? If yes, can you provide some pointers? Thanks!

**Comment by cdanger** [comment]
Once you have create a domai, you can import XACML PolicySets via the REST API, as explained in [section 3.3.4.1 of the User and Programmers Guide](http://authzforce-ce-fiware.readthedocs.io/en/latest/UserAndProgrammersGuide.html#adding-and-updating-policies). You could easily write a script that makes this HTTP POST request for each of your PolicySets, with `curl` for instance.

**Comment by amemon** [comment]
This is great!
