### ISSUE TITLE
Domain not found for application

### ISSUE THREAD

**Issue by gcostantino** [authzforce/server#19]
I'm using Orion Context Broker, Keyrock IdM, Wilma PEP Proxy and Authzforce for the PDP.
When I wanted to perform any action from PEP proxy to PDP I receive the following message: "AZF domain not created for application ...". I tried several strategies to solve the problem, but without considerable results. What's the solution?
Thank you,
Giuseppe

**Comment by cdanger** [comment]
Similar issue has been reported on stackoverflow. This is an issue either in IdM (KeyRock) not creating the AZF domain as expected, when saving role permissions in the IdM GUI ; or an issue with the setup of the PEP (Wilma). You can check on stackoverflow for more info and possible answers:

https://stackoverflow.com/questions/42714175/fiware-authzforce-error-azf-domain-not-created-for-application

https://stackoverflow.com/questions/40513118/azf-domain-not-created-for-application-authzforce
...
You can also ask  KeyRock/Wilma dev team directly on their Github or FIWARE helpdesk.

**Comment by gcostantino** [comment]
I had already seen that question on stackoverflow, but the answers didn't help me.
I noticed this problem when trying to save role permissions in the IdM, but how can I create this domain for the application? Would you kindly explain me how to do? Thank you very much.

**Comment by cdanger** [comment]
The IdM is responsible for creating the domain in this case, when you save the role permissions in the GUI (if the domain is not already created). You may ask the IdM dev team (which I do not belong to) what's going wrong / how to solve it. Sorry I cannot help more at this stage.

**Comment by gcostantino** [comment]
I'll try to ask the IdM dev team. Thank you very much!

**Comment by gcostantino** [comment]
Hi Cyril,
thank you for your support. I have another dubt and FIWARE Online
Documentation couldn't helped me to shed some light.
I don't understand the meaning of "domain" both in Keyrock and in
Authzforce. When I obtain the error "domain not found for application" I
really don't understand the true meaning behind. Is an AZF domain similar
to a Keystone domain? Maybe I have to specify the application id? I do
really am in trouble.


Another tidbit: I was investigating into PEP configuration files and source
.js files and I discovered that the azf_domain var that is passed to the
log console is still "undefined": this causes all my problems! So - just
for testing - I tried to hardcode with my domain id (the one that was
present in AZF default configuration! Moreover, Keystone domain is
"default" and AZF domain is "A0H3....". Why? Is it normal?) and all the
authorization goes on as expected but I receive the message "User
access-token not authorized: user not authorized in AZF for the given
action and resource".
What's the matter?
Thank you in advance,
Giuseppe

2017-09-02 19:52 GMT+02:00 Cyril Dangerville <notifications@github.com>:

**Comment by cdanger** [comment]
"AZF domain not created for application ..." means that the IdM fails to create the AuthzForce domain, and this should be fixed first with help of the IdM team. 

The concept of AuthzForce domain is described in the [installation guide](https://authzforce-ce-fiware.readthedocs.io/en/latest/InstallationAndAdministrationGuide.html#the-concept-of-policy-domain). Basically, in AuthzForce, domains are ways to isolate _things_ from each other, like administrative domains. When I say _things_ I mean: PDP, policy repository, attribute providers, etc. That is to say, each domain have its own dedicated PDP, its own policy repository, etc. In terms of REST API, a domain X is the REST resource `/domains/X` (and everything under it). It makes it easy to restrict access of specific users/roles to specific domain(s), based  on the URL path. 

Typically, depending on your requirements, e.g. the level of granularity or flexibility you are looking for, you can map domains to projects, organizations, etc. In FIWARE IdM, they decide to map AZF domains to applications (as far as I can remember), i.e. one AZF domain is created per application managed in the IdM (the first time you create and save application's role permissions).

It is normal that the Keystone domain and AuthzForce domain don't look the same. They are not supposed to be.

As for your new error in the PEP, you may ask the PEP team. I know you can also increase the log level to get more information by changing `log_config.json`:

```
{
  "appenders": [
    { 
      "type": "console",
      "layout": {
        "type": "pattern",
        "pattern": "%d  - %p: %c - %m",
        "replaceConsole": true
      } 
    }
  ],
  "levels": {
    "Server": "DEBUG",
    "Root": "DEBUG",
    "HTTP-Client": "DEBUG",
    "AZF-Client": "DEBUG",
    "IDM-Client": "DEBUG",
    "Test": "DEBUG"
  }
}

```

Btw, **which versions of IdM/PEP/AZF are you using?**

**Comment by gcostantino** [comment]
I'm using, on Ubuntu 14.04, Keyrock 5.4 (but changeLog says 5.3), Wilma 6.2
and Authzforce 7.0.

2017-09-12 0:17 GMT+02:00 Cyril Dangerville <notifications@github.com>:

**Comment by cdanger** [comment]
Hello, I checked the [IDM installation guide](http://fiware-idm.readthedocs.io/en/latest/admin_guide.html#step-by-step-installation) again which reminded me of the fact that there are actually two parts in IdM (KeyRock): Horizon and Keystone (forks of OpenStack).
So I noticed their [latest Keystone release](https://github.com/ging/keystone/releases) is called: `FIWARE KeyRock 5.4.0`. I assume this is what you have.
But more importantly, their [latest Horizon release](https://github.com/ging/horizon/releases) is `FIWARE KeyRock 5.4.1`. I know that the logic would tell you to have matching versions for both, but I believe you should use this one for Horizon, although you have 5.4.0 for the Keystone part. Please try again with Horizon in version `FIWARE KeyRock 5.4.1`.

**Comment by gcostantino** [comment]
Last horizon commit was on 17 May, so I've already the latest version.

2017-09-12 22:47 GMT+02:00 Cyril Dangerville <notifications@github.com>:

**Comment by gcostantino** [comment]
Hi Cyril,
I solved my problem! Finally the communication goes as expected.
Unfortunately, I have one more issue. I hope I'm not too intrusive.
I wanted to develop a simple testbed in which there is an user A with admin
privileges and an user B without any privilege: so user B can only make GET
requests against Orion Context Broker and user A can make
GET,POST,PUT,DELETE.
In order to make this, I manually (because the graphical interface didn't
allow me) created another user, "utenteprova", which is the user B, as
above and assigned it the role "basic" (via terminal). I assigned the user
"idm" (the user A) the role "admin" as explained in the images #1 and #2.
Then I moved to Horizon interface. I created a role "admin" and a role
"basic", that weren't present and I created a simple permission that allows
GET requests to basic users, using, as resource, "http://localhost:8081/",
which is my PEP Proxy address, that protects Orion. I did it right? Image
#3 explains it.
Finally, I tested it. After getting the token from IdM, I make this request:

curl http://localhost:8081/v2/entities -H 'Accept: application/json' -H
'X-Auth-Token: .......'  | python -m json.tool

With this request I should be able to get all my Orion entities, but I
receive the following messages:

image #4 for the admin user (idm) and image #5 for the trial user
(utenteprova).

Now, there are some strange things! My admin user should have "admin" as
role and not "provider", as my PEP says, and my trial user should have
"basic", but in the response there's no role even!!

Why, in you opinion, this is happening?
Thank you so much,
Giuseppe

2017-09-13 15:26 GMT+02:00 Giuseppe Costantino <
giuseppe.costantino95@gmail.com>:

**Comment by cdanger** [comment]
Hello, glad you solved your problem :-). Could you create a separate issue? Also it seems the image links are broken. They point to the issues on this github repo.

**Comment by sanchit31** [comment]
@gcostantino Hi, Can you please tell how you solved the communication problem. I'm getting the same error: AZF domain not created for application ..."

**Comment by gcostantino** [comment]
Hi, unfortunately I couldn’t solve the problem. The problem seems to be
very weird. Have you got some extra information with respect to the ones I
provided? I didn’t manage to tackle the problem!

Il giorno ven 28 set 2018 alle 13:17 Sanchit Garg <notifications@github.com>
ha scritto:

**Comment by sanchit31** [comment]
Hi @gcostantino, I am using the global instance of Keyrock IdM provided by Fiware Lab. How do I check it's version? I was able to successfully authenticate Wilma PEP Proxy server (installed on my system) with Keyrock. But when I enable azf to true in Wilma config.js, I get this error : **AZF domain not created**. 
When i create roles (under Manager Roles) in Keyrock IdM, I get this error: **Failed to update policies in Access Control GE**. So, I am suspecting that Authzforce and Keyrock are not communicating.  Is there a global instance of Authzforce too? If yes, where can I find it? Or is it integrated with the Keyrock provided by Fiware lab? 

Also, I had locally set up Authzforce on my system and ran it on Tomcat server. How do I create a domain there?

**Comment by gcostantino** [comment]
t exactly the same problem i caught into! Keyrock and Authzforce are truly
not communicating.  You can check all the details  about the version and
all the domains and the rules in the online guide.  I can’t help you no
more because of the fact that I had the same problems and they are already
unsolved :/

Il giorno sab 29 set 2018 alle 17:32 Sanchit Garg <notifications@github.com>
ha scritto:
