### ISSUE TITLE
Authzforce seems not to recognize roles

### ISSUE THREAD

**Issue by gcostantino** [authzforce/server#21]
Hi, I wanted to develop a simple testbed in which there is an user A with admin privileges and an user B without any privilege: so user B can only make GET requests against Orion Context Broker and user A can make GET,POST,PUT,DELETE.
In order to make this, I manually (because the graphical interface didn't allow me) created another user, "utenteprova", which is the user B, as above and assigned it the role "basic" (via terminal). I assigned the user "idm" (the user A) the role "admin" as explained in the images #1 and #2.
Then I moved to Horizon interface. I created a role "admin" and a role "basic", that weren't present and I created a simple permission that allows GET requests to basic users, using, as resource, "http://localhost:8081/", which is my PEP Proxy address, that protects Orion. I did it right? Image #3 explains it.
Finally, I tested it. After getting the token from IdM, I make this request:

curl http://localhost:8081/v2/entities -H 'Accept: application/json' -H 'X-Auth-Token: .......'  | python -m json.tool

With this request I should be able to get all my Orion entities, but I receive the following messages:

image #4 for the admin user (idm) and image #5 for the trial user (utenteprova).

Now, there are some strange things! My admin user should have "admin" as role and not "provider", as my PEP says, and my trial user should have "basic", but in the response there's no role even!!

Why, in you opinion, this is happening?
Thank you so much,
Giuseppe

![1](https://user-images.githubusercontent.com/29159509/31463806-a4067366-aecf-11e7-9332-6471c29d600e.png)
![2](https://user-images.githubusercontent.com/29159509/31463807-a42a46b0-aecf-11e7-90df-9f3d102d9b13.png)
![3](https://user-images.githubusercontent.com/29159509/31463810-a449c652-aecf-11e7-8081-5f1774f40dab.png)
![4](https://user-images.githubusercontent.com/29159509/31463812-a46c17a2-aecf-11e7-8edd-69df17bf27b9.png)
![5](https://user-images.githubusercontent.com/29159509/31463813-a48abae0-aecf-11e7-9889-61550b9fd70b.png)

**Comment by cdanger** [comment]
Regarding images 4 and 5, the wrong list of user roles here is coming from the idm. Therefore, the issue at this point relates to the idm, not AuthzForce. You should ask the idm or PEP dev team why the returned list of user roles is not what you expect. However, I can pinpoint two things that seem wrong to me so far:
1. I see no reason why you were not able to create another user with the Idm GUI. Did you ask for support?
2. You were able to assign roles "admin" and "basic" to some users from the terminal, although these roles were not visible/defined in the IdM GUI yet. This does not make sense and makes me thing there may be a lack of consistency (database sync ?) between the API you used from the terminal on the one hand, and the IdM GUI or API used by the PEP to retrieve user roles on the other hand. 

Besides, if I remember right, in the IdM GUI, roles must be application-specific. So did you create the roles 'admin' and 'basic' at the level of the application with ID "00d230d493.....b" (copied from the screenshot above)? Also you should try to assign these new application-specific roles to your users with the IdM GUI.
Last, I suggest you reproduce the request done by the PEP against the IdM to get the user info from the authentication token, and you check the response. As a hint, there should be some logs starting with "IDM-Client" before the ones you showed here with something like "GET /v3/access-tokens/xxxxxxxxxxxxx". If you want more info on this request, and the PEP dev team is not helping, check the [code](https://github.com/ging/fiware-pep-proxy/blob/master/lib/idm.js).
