### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by reddyalready** [authzforce/server#22]
Is this repo/code licensed under a specific license? AuthZForce Core seems to be licensed Apache 2.0, is the server the same? 

Thanks!

**Comment by cdanger** [comment]
The server project (including `webapp` and `rest-service` maven projects) is itself under GPL v3, except for one Java class (JettisonReader). However, must of the code are in its dependencies, i.e. AuthzForce libraries like AuthzForce Core, which are under Apache license as you mentioned.

**Comment by reddyalready** [comment]
Great, thank you so much for your quick response Cyril!
