### ISSUE TITLE
Unable to send simple request in JSON format

### ISSUE THREAD

**Issue by tresoldigiorgio** [authzforce/server#33]
Im'm using Authzforce 8.0.1 on docker.
I try to to send this request to pdp:
`{
  "Request" : {
      	"ReturnPolicyIdList" : false
  }
}`
and the response are:
`{
"error":{
"message": "Invalid parameters: cvc-complex-type.4: Attribute 'ReturnPolicyIdList' must appear on element 'Request'."
}
}`
is a bug? I'm unable to send any type of request.

Thanks

**Comment by cdanger** [comment]
I assume you are using Content-Type `application/json`. In this case, you must add prefix `@` to the JSON key when it corresponds to an attribute in the XACML/XML schema.
You also need a `CombinedDecision` attribute and at least one `Attributes` element to be compliant with XACML schema.

For example:
```js
{"Request":{"@ReturnPolicyIdList":"false","@CombinedDecision":"false","Attributes":{"@Category":"urn:oasis:names:tc:xacml:1.0:subject-category:access-subject"}}}
```
For more JSON examples, check issue #27 .
