### ISSUE TITLE
[SHOULD] Double tag FIWARE Release

### ISSUE THREAD

**Issue by jason-fox** [authzforce/server#36]
Could you please add an additional tags to  indicate which version aligns with which  FIWARE  release- you can see a similar examples here:

[IoT Agent JSON](https://github.com/telefonicaid/iotagent-json/releases)

* af26edd - `FIWARE 7.5.1`, `FIWARE_7.5`, `FIWARE_7.4`

**Comment by cdanger** [comment]
af26edd tagged FIWARE_7.5.1
