### ISSUE TITLE
[MUST] Update README on master branch

### ISSUE THREAD

**Issue by jason-fox** [authzforce/server#37]
Several PRs have been accepted into `develop`, but no release has been made since 8.0.1, therefore some *fixed* issues do not display as *fixed* on the `master` branch

For example:

* README must have a QA section
* README must have a training section

This is just a placeholder to indicate that a release is required to complete the fix. Please close this issue once a new release has been completed.

**Comment by cdanger** [comment]
Fixed in 8882cf820b98067a8dd217ee6a29f36e47505d54
