### ISSUE TITLE
Release 8.0.1 Versioned Documentation is inactive on RTD

### ISSUE THREAD

**Issue by jason-fox** [authzforce/server#40]
On the Authzforce ReadtheDocs project, release 8.0.1 versioned documentation is  not displayed

- Goto https://readthedocs.org/projects/authzforce-ce-fiware/versions/
- Ensure that **active** checkmark is ticked against relevant release tag

**Comment by cdanger** [comment]
https://authzforce-ce-fiware.readthedocs.io/en/release-8.0.1/
