### ISSUE TITLE
Failed to find a root PolicySet with id

### ISSUE THREAD

**Issue by andrasnemes** [authzforce/server#45]
Hi AuthZForce Team,

I'm trying to enter a PolicySet via the `POST /pap/policies` endpoint:

`<?xml version="1.0" encoding="UTF-8"?>
<PolicySet xmlns="urn:oasis:names:tc:xacml:3.0:core:schema:wd-17" PolicyCombiningAlgId="urn:oasis:names:tc:xacml:3.0:policy-combining-algorithm:deny-overrides" PolicySetId="PolicySetWithEmailRuleAnyActionAnyResource" Version="1.0">
   <Description>TestPolicySet</Description>
   <Target />
   <Policy PolicyId="urn:oasis:names:tc:xacml:3.0:example:EmailNamespaceAnyActionAnyResource" Version="1.0" RuleCombiningAlgId="identifier:rule-combining-algorithm:deny-overrides">
      <Description>Medi Corp access control policy</Description>
      <Target />
      <Rule RuleId="urn:oasis:names:tc:xacml:3.0:example:EmailRule" Effect="Permit">
         <Description>Any subject with an e-mail name in the med.example.com domain
          can perform any action on any resource.</Description>
         <Target>
            <AnyOf>
               <AllOf>
                  <Match MatchId="urn:oasis:names:tc:xacml:1.0:function:rfc822Name-match">
                     <AttributeValue DataType="http://www.w3.org/2001/XMLSchema#string">med.example.com</AttributeValue>
                     <AttributeDesignator MustBePresent="false" Category="urn:oasis:names:tc:xacml:1.0:subject-category:access-subject" AttributeId="urn:oasis:names:tc:xacml:1.0:subject:subject-id" DataType="urn:oasis:names:tc:xacml:1.0:data-type:rfc822Name" />
                  </Match>
               </AllOf>
            </AnyOf>
         </Target>
      </Rule>
   </Policy>
</PolicySet>`

I get the following error (400 bad request):

`{
   "error": {
       "message": "Failed to find a root PolicySet with id = 'PolicySetWithEmailRuleAnyActionAnyResource', Version=1.0,EarliestVersion=,LatestVersion=: Matched PolicySet 'PolicySetWithEmailRuleAnyActionAnyResource' (version 1.0) is invalid or its content is unavailable"
   }
}`

I don't understand this message. What is this required root and how do I add it to the XACML message? I see that there is a default policy set called "root" but I'm not sure what it is for and how to refer to it.

Strangely enough the policy set seems to have been saved anyway, I can retrieve it via `GET /pap/policies/PolicySetWithEmailRuleAnyActionAnyResource/1.0` endpoint.

Ultimately I'm having problems adding even a simple policy set that returns a 200, i.e. goes through without validation errors.

Thanks for your help,
Andras Nemes

**Comment by cdanger** [comment]
This RuleCombiningAlgId is invalid: 'identifier:rule-combining-algorithm:deny-overrides' . Could you fix and try again?
Also which version of AuthzForce Server do you use?

**Comment by andrasnemes** [comment]
Thanks for your response. 

You were right, that was the issue, I corrected the algo ID to urn:oasis:names:tc:xacml:3.0:rule-combining-algorithm:deny-overrides and the policy set was accepted. 

FYI: I'm testing the policy examples from [http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-os-en.html](url), the XML I mentioned is posted under Example 1. That example includes the same rule combining algorithm ID that I corrected now.

I'm on version 8.1.0.

I'm curious and would appreciate some explanation here: what is the role of the root policy set in AuthzForce? 

Thanks for your help,
Andras

**Comment by cdanger** [comment]
> FYI: I'm testing the policy examples from [http://docs.oasis-open.org/xacml/3.0/xacml-3.0-core-spec-os-en.html](url), the XML I mentioned is posted under Example 1. That example includes the same rule combining algorithm ID that I corrected now.

Indeed, that's a typo in the spec right there. I'll report it to the XACML TC for later versions. Thanks for the tip.

> I'm curious and would appreciate some explanation here: what is the role of the root policy set in AuthzForce?

See the [User guide, §5.3.5.6](https://authzforce-ce-fiware.readthedocs.io/en/release-8.1.0/UserAndProgrammersGuide.html#policy-decision-pdp-properties)

> EDIT: do you have a forum where people can ask questions about AuthzForce? I'm not sure if opening a GitHub issue or raising a question on Stackoverflow for everything is a good way to go.

As mentioned in the [Support section](https://github.com/authzforce/server#support) of the README, you may use AuthzForce mailing list.

My concern is that authzforce server 8.1.0 should not save invalid policies at all anymore and give back a more meaningful error message in the body of the 400 (Bad Request) response, so I'll give it a try on my side with your policy (the invalid one).
