### ISSUE TITLE
Problem with Authzforce installation

### ISSUE THREAD

**Issue by fernandorr21** [authzforce/server#54]
I tried to install by package (authzforce-ce-server-dist-8.1.0.deb) and I get an error in tomcat, /var/log/tomcat8/authzforce-ce/error.log:

2020-07-17 11:05:20,822|ERROR|localhost-startStop-1|org.springframework.web.context.ContextLoader:351|Context initialization failed|
org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from ServletContext resource [/WEB-INF/beans.xml]; nested exception is org.springframework.beans.FatalBeanException: Invalid NamespaceHandler class [org.apache.cxf.bus.spring.NamespaceHandler] for namespace [http://cxf.apache.org/core]: problem with handler class file or dependent class; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:414)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:181)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:217)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:125)
	at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:94)
	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:129)
	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:613)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:514)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4770)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5236)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:624)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1834)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.springframework.beans.FatalBeanException: Invalid NamespaceHandler class [org.apache.cxf.bus.spring.NamespaceHandler] for namespace [http://cxf.apache.org/core]: problem with handler class file or dependent class; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.springframework.beans.factory.xml.DefaultNamespaceHandlerResolver.resolve(DefaultNamespaceHandlerResolver.java:140)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1406)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1401)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:172)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:142)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:94)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:508)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:392)
	... 26 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at org.apache.cxf.bus.spring.NamespaceHandler.init(NamespaceHandler.java:33)
	at org.springframework.beans.factory.xml.DefaultNamespaceHandlerResolver.resolve(DefaultNamespaceHandlerResolver.java:131)
	... 33 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1364)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1185)
	... 35 common frames omitted
2020-07-17 11:05:21,172|WARN |localhost-startStop-1|org.springframework.web.context.support.XmlWebApplicationContext:1005|Exception thrown from LifecycleProcessor on context close|
java.lang.IllegalStateException: LifecycleProcessor not initialized - call 'refresh' before invoking lifecycle methods via the context: Root WebApplicationContext: startup date [Fri Jul 17 11:05:17 CEST 2020]; root of context hierarchy
	at org.springframework.context.support.AbstractApplicationContext.getLifecycleProcessor(AbstractApplicationContext.java:417)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1002)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:961)
	at org.springframework.web.context.ContextLoader.closeWebApplicationContext(ContextLoader.java:581)
	at org.springframework.web.context.ContextLoaderListener.contextDestroyed(ContextLoaderListener.java:116)
	at org.apache.catalina.core.StandardContext.listenerStop(StandardContext.java:4817)
	at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5474)
	at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:154)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:754)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:730)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:624)
	at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1834)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by cdanger** [comment]
Could you post the full tomcat logs including the last startup logs at the beginning?

**Comment by fernandorr21** [comment]
20-Jul-2020 16:39:58.387 INFORMACIÓN [Thread-3] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8080"]
20-Jul-2020 16:40:04.289 INFORMACIÓN [Thread-3] org.apache.catalina.core.StandardService.stopInternal Parando servicio [Catalina]
20-Jul-2020 16:40:14.365 INFORMACIÓN [Thread-3] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8080"]
20-Jul-2020 16:40:44.694 ADVERTENCIA [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
20-Jul-2020 16:40:44.827 ADVERTENCIA [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
20-Jul-2020 16:40:44.831 ADVERTENCIA [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common/classes], exists: [false], isDirectory: [false], canRead: [false]
20-Jul-2020 16:40:44.837 ADVERTENCIA [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/common], exists: [false], isDirectory: [false], canRead: [false]
20-Jul-2020 16:40:45.021 ADVERTENCIA [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
20-Jul-2020 16:40:45.023 ADVERTENCIA [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
20-Jul-2020 16:40:45.023 ADVERTENCIA [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server/classes], exists: [false], isDirectory: [false], canRead: [false]
20-Jul-2020 16:40:45.024 ADVERTENCIA [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/server], exists: [false], isDirectory: [false], canRead: [false]
20-Jul-2020 16:40:45.030 ADVERTENCIA [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
20-Jul-2020 16:40:45.034 ADVERTENCIA [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/var/lib/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
20-Jul-2020 16:40:45.038 ADVERTENCIA [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared/classes], exists: [false], isDirectory: [false], canRead: [false]
20-Jul-2020 16:40:45.042 ADVERTENCIA [main] org.apache.catalina.startup.ClassLoaderFactory.validateFile Problem with directory [/usr/share/tomcat8/shared], exists: [false], isDirectory: [false], canRead: [false]
20-Jul-2020 16:41:40.983 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.39 (Ubuntu)
20-Jul-2020 16:41:41.003 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Sep 9 2019 19:47:51 UTC
20-Jul-2020 16:41:41.006 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.39.0
20-Jul-2020 16:41:41.010 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
20-Jul-2020 16:41:41.022 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-74-generic
20-Jul-2020 16:41:41.026 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
20-Jul-2020 16:41:41.034 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-11-openjdk-amd64
20-Jul-2020 16:41:41.038 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.5+10-post-Ubuntu-0ubuntu1.118.04
20-Jul-2020 16:41:41.051 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Private Build
20-Jul-2020 16:41:41.054 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /var/lib/tomcat8
20-Jul-2020 16:41:41.062 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/share/tomcat8
20-Jul-2020 16:41:41.074 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
20-Jul-2020 16:41:41.093 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
20-Jul-2020 16:41:41.101 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
20-Jul-2020 16:41:41.102 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/var/lib/tomcat8/conf/logging.properties
20-Jul-2020 16:41:41.103 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
20-Jul-2020 16:41:41.110 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
20-Jul-2020 16:41:41.115 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.xml.accessExternalSchema=http
20-Jul-2020 16:41:41.118 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms1024m
20-Jul-2020 16:41:41.131 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx1024m
20-Jul-2020 16:41:41.132 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseConcMarkSweepGC
20-Jul-2020 16:41:41.140 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
20-Jul-2020 16:41:41.150 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
20-Jul-2020 16:41:41.163 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
20-Jul-2020 16:41:41.172 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
20-Jul-2020 16:41:41.182 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/var/lib/tomcat8
20-Jul-2020 16:41:41.190 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/share/tomcat8
20-Jul-2020 16:41:41.195 INFORMACIÓN [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/tmp/tomcat8-tomcat8-tmp
20-Jul-2020 16:41:41.202 INFORMACIÓN [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Cargada la biblioteca nativa APR de Apache Tomcat [1.2.21] con la versión APR [1.6.3].
20-Jul-2020 16:41:41.214 INFORMACIÓN [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Capacidades APR: IPv6 [true], enviar fichero [true], aceptar filtros [false], aleatorio [true].
20-Jul-2020 16:41:41.217 INFORMACIÓN [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
20-Jul-2020 16:41:41.338 INFORMACIÓN [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL inicializado correctamente [OpenSSL 1.1.1  11 Sep 2018]
20-Jul-2020 16:41:42.265 INFORMACIÓN [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
20-Jul-2020 16:41:42.950 INFORMACIÓN [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
20-Jul-2020 16:41:43.219 INFORMACIÓN [main] org.apache.catalina.startup.Catalina.load Initialization processed in 55182 ms
20-Jul-2020 16:41:46.403 INFORMACIÓN [main] org.apache.catalina.core.StandardService.startInternal Arrancando servicio [Catalina]
20-Jul-2020 16:41:46.404 INFORMACIÓN [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.39 (Ubuntu)
20-Jul-2020 16:41:46.896 INFORMACIÓN [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Desplieque del descriptor de configuración [/etc/tomcat8/Catalina/localhost/authzforce-ce.xml]
20-Jul-2020 16:43:39.615 INFORMACIÓN [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars Al menos un JAR, que se ha explorado buscando TLDs, aún no contenía TLDs. Activar historial de depuración para este historiador para una completa lista de los JARs que fueron explorados y de los que nos se halló TLDs. Saltarse JARs no necesarios durante la exploración puede dar lugar a una mejora de tiempo significativa en el arranque y compilación de JSP .
20-Jul-2020 16:43:53.898 GRAVE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
20-Jul-2020 16:43:54.255 ADVERTENCIA [localhost-startStop-1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [347] milliseconds.
20-Jul-2020 16:43:54.266 GRAVE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Falló en arranque del Contexto [/authzforce-ce] debido a errores previos
20-Jul-2020 16:43:55.027 INFORMACIÓN [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of configuration descriptor [/etc/tomcat8/Catalina/localhost/authzforce-ce.xml] has finished in [128.130] ms
20-Jul-2020 16:43:55.073 INFORMACIÓN [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Despliegue del directorio [/var/lib/tomcat8/webapps/ROOT] de la aplicación web
20-Jul-2020 16:44:00.953 INFORMACIÓN [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars Al menos un JAR, que se ha explorado buscando TLDs, aún no contenía TLDs. Activar historial de depuración para este historiador para una completa lista de los JARs que fueron explorados y de los que nos se halló TLDs. Saltarse JARs no necesarios durante la exploración puede dar lugar a una mejora de tiempo significativa en el arranque y compilación de JSP .
20-Jul-2020 16:44:01.220 INFORMACIÓN [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/var/lib/tomcat8/webapps/ROOT] has finished in [6.177] ms
20-Jul-2020 16:44:01.302 INFORMACIÓN [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
20-Jul-2020 16:44:01.459 INFORMACIÓN [main] org.apache.catalina.startup.Catalina.start Server startup in 138221 ms

**Comment by cdanger** [comment]
The logs show you are using Java 11:
```
JVM Version: 11.0.5+10-post-Ubuntu-0ubuntu1.118.04
```

AuthzForce requires Java 8 and supports only that, so you have to change the JVM version that Tomcat is running on.

**Comment by fernandorr21** [comment]
it's true thank you very much, but i can't install authzforce via docker. I want to work on a stage with wilma and authzforce, it is better to configure it using docker, but I always get this error:



13-Jul-2020 23:02:32.167 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.35
13-Jul-2020 23:02:32.280 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Nov 3 2018 17:39:20 UTC
13-Jul-2020 23:02:32.296 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.35.0
13-Jul-2020 23:02:32.305 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
13-Jul-2020 23:02:32.308 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-109-generic
13-Jul-2020 23:02:32.318 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
13-Jul-2020 23:02:32.332 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
13-Jul-2020 23:02:32.384 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_181-8u181-b13-2~deb9u1-b13
13-Jul-2020 23:02:32.385 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
13-Jul-2020 23:02:32.396 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
13-Jul-2020 23:02:32.401 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
13-Jul-2020 23:02:32.410 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
13-Jul-2020 23:02:32.414 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
13-Jul-2020 23:02:32.436 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.security.egd=file:/dev/./urandom
13-Jul-2020 23:02:32.439 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
13-Jul-2020 23:02:32.484 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djavax.xml.accessExternalSchema=all
13-Jul-2020 23:02:32.501 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms1024m
13-Jul-2020 23:02:32.508 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2048m
13-Jul-2020 23:02:32.515 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseConcMarkSweepGC
13-Jul-2020 23:02:32.533 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
13-Jul-2020 23:02:32.543 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
13-Jul-2020 23:02:32.564 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
13-Jul-2020 23:02:32.603 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
13-Jul-2020 23:02:32.616 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
13-Jul-2020 23:02:32.621 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
13-Jul-2020 23:02:32.641 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
13-Jul-2020 23:02:32.648 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library [1.2.18] using APR version [1.5.2].
13-Jul-2020 23:02:32.664 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
13-Jul-2020 23:02:32.675 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
13-Jul-2020 23:02:32.834 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized [OpenSSL 1.1.0f  25 May 2017]
13-Jul-2020 23:02:36.801 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
13-Jul-2020 23:02:37.410 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
13-Jul-2020 23:02:38.252 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
13-Jul-2020 23:02:38.352 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
13-Jul-2020 23:02:38.384 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 25561 ms
13-Jul-2020 23:02:39.751 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
13-Jul-2020 23:02:39.792 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.35
13-Jul-2020 23:02:40.542 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor [/usr/local/tomcat/conf/Catalina/localhost/authzforce-ce.xml]
13-Jul-2020 23:03:38.492 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
13-Jul-2020 23:03:38.955 WARNING [localhost-startStop-1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [350] milliseconds.
13-Jul-2020 23:03:39.074 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/authzforce-ce] startup failed due to previous errors
13-Jul-2020 23:03:39.906 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of configuration descriptor [/usr/local/tomcat/conf/Catalina/localhost/authzforce-ce.xml] has finished in [59,364] ms
13-Jul-2020 23:03:40.039 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/manager]
13-Jul-2020 23:03:42.682 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/manager] has finished in [2,643] ms
13-Jul-2020 23:03:42.724 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT]
13-Jul-2020 23:03:43.353 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/ROOT] has finished in [630] ms
13-Jul-2020 23:03:43.393 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/host-manager]
13-Jul-2020 23:03:44.971 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/host-manager] has finished in [1,551] ms
13-Jul-2020 23:03:44.979 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/docs]
13-Jul-2020 23:03:46.032 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/docs] has finished in [1,053] ms
13-Jul-2020 23:03:46.075 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/examples]
13-Jul-2020 23:03:53.996 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/examples] has finished in [7,921] ms
13-Jul-2020 23:03:54.154 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
13-Jul-2020 23:03:54.440 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
13-Jul-2020 23:03:54.517 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 76084 ms
I have this file .yml:


image: fiware/authzforce-ce-server:release-8.1.0
hostname: authzforce
container_name: fiware-authzforce


networks:
  default:
    ipv4_address: 172.18.1.12
ports:
  - "8080:8080" # localhost:8080
volumes:
  - ./authzforce/domains:/opt/authzforce-ce-server/data/domains
healthcheck:
  test: curl --fail -s http://localhost:8080/authzforce-ce/version || exit 1

**Comment by fernandorr21** [comment]
I had to continue working without volumes in authzforce. However, I have had another problem with PEP PROXY and authzforce:

curl -X GET 'http://localhost:1027/v2/entities' -H 'X-Auth-Token: 3a74f742f56dd40f1a307624c3d917f4575005b7'
2020-07-16 18:27:15.421  - INFO: IDM-Client - Checking token with IDM...
2020-07-16 18:27:16.969  - INFO: AZF-Client - Checking auth with AZF...
2020-07-16 18:27:16.969  - INFO: AZF-Client - Checking authorization 
2020-07-16 18:27:17.065  - ERROR: Root - Domain not found:  

I have verified that this error is common, but I cannot fix it.

**Comment by cdanger** [comment]
> it's true thank you very much, but i can't install authzforce via docker. I want to work on a stage with wilma and authzforce, it is better to configure it using docker, but I always get this error:
> ...
> 13-Jul-2020 23:02:40.542 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor [/usr/local/tomcat/conf/Catalina/localhost/authzforce-ce.xml]
> 13-Jul-2020 23:03:38.492 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
> ...

I would need the other logs in /var/log/tomcat8/localhost-XXX.log and /var/log/tomcat8/authzforce-ce/error.log to find out the actual error behind it.

**Comment by cdanger** [comment]
> I had to continue working without volumes in authzforce. However, I have had another problem with PEP PROXY and authzforce:
> 
> curl -X GET 'http://localhost:1027/v2/entities' -H 'X-Auth-Token: 3a74f742f56dd40f1a307624c3d917f4575005b7'
> 2020-07-16 18:27:15.421 - INFO: IDM-Client - Checking token with IDM...
> 2020-07-16 18:27:16.969 - INFO: AZF-Client - Checking auth with AZF...
> 2020-07-16 18:27:16.969 - INFO: AZF-Client - Checking authorization
> 2020-07-16 18:27:17.065 - ERROR: Root - Domain not found:
> 
> I have verified that this error is common, but I cannot fix it.

Well, this is an issue with the PEP proxy (Wilma) and probaly the IDM (Keyrock), so you'd better ask the Wilma developers, which I am not part of. Yet, I remember the IDM is supposed to create the AuthzForce domain when you create a new application in the IDM (KeyRock), then the PEP proxy (Wilma) is supposed to find this domain based on the application ID in the request. But I am just guessing here. Did you check on Stackoverflow and Wilma github repository? Maybe check this one, especially the comments:
https://stackoverflow.com/questions/50412682/domain-not-found-azf-domain-not-created-for-application

**Comment by fernandorr21** [comment]
Thank you very much, I have already fixed everything, for volumes, the failure was that there was a badly created domain in the local folder. Then domain not found is because authz_domain_id was configured in mysql with a wrong value which I was working on

**Comment by cdanger** [comment]
Alright then :-) I consider this closed.
