### ISSUE TITLE
Need Help in 

### ISSUE THREAD

**Issue by aritrabera06** [authzforce/server#60]
Hi,

I am unable to debug and run my own custom test cases on my IDE. Is there any documentation available to run them on our IDE?

Looking forward to hearing back from you.

Best

**Comment by cdanger** [comment]
Too vague. Is this relevant to AuthzForce Server in any way? Please give enough information for us to reproduce the issue.

**Comment by cdanger** [comment]
No reply for more than 2 weeks, closing.
