### ISSUE TITLE
JSONObject support

### ISSUE THREAD

**Issue by securedimensions** [authzforce/server#61]
### Overview
[GeoXACML](https://www.ogc.org/standards/geoxacml) is an OGC standard that extends OASIS [XACML](https://www.oasis-open.org/committees/tc_home.php?wg_abbrev=xacml) with the `geometry` data type and related functions. The current work in progress is standardizing the v3.0.

GeoXACML allows encoding of geometries via
* Well-Known-Text (String)
* GML (XML)

In the [OGC GeoXACML 3.0 SWG](https://www.ogc.org/projects/groups/geoxacmlswg), we are currently working on a [GeoJSON](https://tools.ietf.org/html/rfc7946) geometry encoding extension. The plan is to leverage the GeoJSON GeometryObject inside the Attribute Value of the XACML 3.0 JSON Profile. The following example illustrates the approach.

````json
"Attribute": [
        {
            "AttributeId": "urn:ogc:geoxacml:3.0:subjet-location",
            "DataType": "urn:ogc:def:dataType:geoxacml:1.0:geometry",
            "Value": [
                {
                    "geometry": {
                        "type": "Point",
                        "coordinates": [102.0,0.5]
                    }
                }
            ]
        }
    ]
````

### Issue
But, when running a request using the GeoJSON encoding on the AuthzForce Server 9.0.1 (that has loaded the GeoXACML extension) the following exception is returned:

````json
{"error":"Unsupported type of item in Value array of attribute '[category='urn:oasis:names:tc:xacml:3.0:attribute-category:environment', issuer=null, id='urn:ogc:geoxacml:3.0:subjet-location']': JSONObject"}
````
_AuthzForce exception for ADR with JSONObject as Attribute Value_

And from the log:
````
Response-Code: 501
Content-Type: application/xacml+json
Headers: {Content-Type=[application/xacml+json], Date=[Mon, 08 Feb 2021 13:11:22 GMT]}
Payload: {"error":"Unsupported type of item in Value array of attribute '[category='urn:oasis:names:tc:xacml:3.0:attribute-category:environment', issuer=null, id='urn:ogc:geoxacml:3.0:subjet-location']': JSONObject"}
````
_AuthzForce Server exception response_

To reproduce the issue, please load the GeoXACML extension onto the AuthzForce Server 9.0. You can obtain the GeoXACML extension from the public Github repo: [GeoXACML Basic](https://github.com/securedimensions/authzforce-geoxacml-basic). The INSTALL.md explains how to build and deploy the extension.

And then send the following request to the AuthzForce server:

````json
{
    "Request": {
        "ReturnPolicyIdList": false,
        "CombinedDecision": false,
        "Category": [
            {
                "CategoryId": "urn:oasis:names:tc:xacml:1.0:subject-category:access-subject",
                "Attribute": [
                    {
                        "IncludeInResult": false,
                        "AttributeId": "urn:oasis:names:tc:xacml:1.0:subject:subject-id",
                        "DataType": "http://www.w3.org/2001/XMLSchema#string",
                        "Value": ["Julius Hibbert"]
                    }
                ]
            },
            {
                "CategoryId": "urn:oasis:names:tc:xacml:3.0:attribute-category:resource",
                "Attribute": [
                    {
                        "IncludeInResult": false,
                        "AttributeId": "urn:oasis:names:tc:xacml:1.0:resource:resource-id",
                        "DataType": "http://www.w3.org/2001/XMLSchema#anyURI",
                        "Value": ["http://medico.com/record/patient/BartSimpson"]
                    }
                ]
            },
            {
                "CategoryId": "urn:oasis:names:tc:xacml:3.0:attribute-category:action",
                "Attribute": [
                    {
                        "IncludeInResult": false,
                        "AttributeId": "urn:oasis:names:tc:xacml:1.0:action:action-id",
                        "DataType": "http://www.w3.org/2001/XMLSchema#string",
                        "Value": ["read"]
                    }
                ]
            },
            {
                "CategoryId": "urn:oasis:names:tc:xacml:3.0:attribute-category:environment",
                "Attribute": [
                    {
                        "IncludeInResult": false,
                        "AttributeId": "urn:ogc:geoxacml:3.0:subjet-location",
                        "DataType": "urn:ogc:def:dataType:geoxacml:1.0:geometry",
                        "Value": {
                            "geometry": {
                                "type": "Point",
                                "coordinates": [102.0,0.5]
                            }
                        }
                    }
                ]
            }
        ]
    }
}
````
_ADR using GeoJSON geometry encoding_

### Resolution
Allowing any JSON Object for the Value is a potential security hazard. 

Perhaps it is possible to allow a JSON Object processing where the extension would have to specify the Parser. In our case, that would be the `org.wololo.jts2geojson.GeoJSONReader`. Another solution perhaps would be to allow a String processing of the JSON Object?

Looking forward to a way that allows us to encode geometries via GeoJSON...

Best
Andreas

### How to reproduce - additional info 

From Andreas's message on authzforce-users mailing list:

*Checkout https://github.com/securedimensions/authzforce-geoxacml-basic, follow the instructions in INSTALL.md to enable the BASIC support for geometry datatype to your server 9.0. I’ve just merged develop with master to support the latest AuthzForce version and Java 11.*

**Comment by cdanger** [comment]
Now the release 10.0.0 is out and implements the requested feature. In your AuthzForce Datatype extension (for GeoXACML), you will have access to the JSON object in the `content` argument of the `Factory#getInstance(content,...)` method, as a [SerializableJsonObject](https://javadoc.io/doc/org.ow2.authzforce/authzforce-ce-core-pdp-io-xacml-json/latest/org/ow2/authzforce/core/pdp/io/xacml/json/SerializableJSONObject.html). The `SerializableJsonObject#get()` method gives you the original JSON object from the XACML request. You can find an example of code for this in the [CustomJsonObjectBasedAttributeValue class](https://github.com/authzforce/core/blob/develop/pdp-testutils/src/main/java/org/ow2/authzforce/core/pdp/testutil/ext/CustomJsonObjectBasedAttributeValue.java#L96).

To make this work, you first have to update the authzforce dependencies of your Datatype extension:
- authzforce-ce-core-pdp-api: 18.0.1,
- Add authzforce-ce-core-pdp-io-xacml-json: 17.1.0. 

Regarding your comment *Allowing any JSON Object for the Value is a potential security hazard*, there are several possible mitigations given in the [documentation](https://authzforce-ce-fiware.readthedocs.io/en/release-10.0.0/InstallationAndAdministrationGuide.html#xml-and-json-security). One of them consists to use a custom JSON schema for validation and this JSON schema would only allow GeoXACML/geometry values as JSON objects in XACML Request Attribute Values. For that, you set the webapp environment property `org.ow2.authzforce.domains.xacmlJsonSchemaRelativePath` to the custom JSON schema file in `/opt/authzforce-ce-server/conf`, for example [Request-with-geometry.schema.json](https://github.com/authzforce/server/blob/release-10.0.0/webapp/src/test/resources/authzforce-ce-server/conf/Request-with-geometry.schema.json). This one refers to [Geometry.schema.json](https://github.com/authzforce/server/blob/release-10.0.0/webapp/src/test/resources/authzforce-ce-server/conf/Geometry.schema.json) (through intermediate schema [common-std-with-geometry.schema.json](https://github.com/authzforce/server/blob/release-10.0.0/webapp/src/test/resources/authzforce-ce-server/conf/common-std-with-geometry.schema.json) which comes from the [GeoJSON website](https://geojson.org/schema/Geometry.json) itself, so we know it complies with the official format.
