### ISSUE TITLE
Namespace declaration error for structured Attributes

### ISSUE THREAD

**Issue by securedimensions** [authzforce/server#62]
The [GeoXACML extension](https://github.com/securedimensions/authzforce-geoxacml-basic/tree/develop) supports the data type `Geometry`. The encoding for the `Geometry` AttributeValue can be done via String or XML:

* String: Based on [Well Knwon Text](https://portal.ogc.org/files/?artifact_id=25355)
* XML: Based on [Geography Markup Language](https://www.ogc.org/standards/gml)

The `GeoXACML` extension can be build via `mvn install` and be deployed onto the AuthzForce CE Server as described in the documentation.

When loading the `GeoXACML` policy for validating the Geometry encoding via GML, the following exception is thrown by the AuthzForce Server:

To reproduce the error, 

* load the `GeoXACML extension` onto the server
* update the `pdp.properties` with the file from the folder `/src/main/resources/updateProperties.xml`
* upload the `GeoXACML policy` from the folder `/src/main/resources/conformance/geoxacml-3.0/core/policy-broken.xml`

When loading the policy, the server throws the exception `Duplicate declaration of namespace prefix 'gml' (empty string refers to default namespace)`

Best
Andreas

**Comment by cdanger** [comment]
I think you meant `/src/test/resources/conformance/...` instead of `/src/main/resources/conformance/...` ;-)

**Comment by cdanger** [comment]
If you want a quick fix, you may try replacing the authzforce-ce-core-pdp-api jar in /opt/authzforce-ce-server/webapp/WEB-INF/lib with the new version 18.0.1.
Else you may wait for the next AuthzForce server release that should happen by the end of the week.

**Comment by cdanger** [comment]
Now release 10.0.0 is out, which should fix the issue.
