### ISSUE TITLE
Performance and Components

### ISSUE THREAD

**Issue by jainh** [authzforce/server#7]
Hi,

Is there a way to clearly separate Xacml-PeP, PAP, PDP and PIP ?  If i want to detach or deploy them separately, how is that feasible ? Also, wondering have you done any performance benchmarking around this implementation ?

**Comment by cdanger** [comment]
Hello jainh,
thanks for your interest in AuthzForce. Please send an email to [AuthzForce mailing list](http://scr.im/azteam)  for this purpose. This page is only for reporting issues or requesting missing features. I also strongly recommend you send two different emails to separate the two different subjects in your question. Thanks :)
